steps:
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
          docker build -t gcr.io/$PROJECT_ID/hello:${BRANCH_NAME}-${SHORT_SHA} -t hello:latest .

  - id: 'publish'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
          docker push gcr.io/$PROJECT_ID/hello:${BRANCH_NAME}-${SHORT_SHA}
          docker push gcr.io/$PROJECT_ID/hello:latest