steps:

  # Build
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
          docker build -t gcr.io/$PROJECT_ID/hello:${SHORT_SHA} -t gcr.io/$PROJECT_ID/hello:latest -t gcr.io/$PROJECT_ID/hello:${_IMAGE_TAG} .

  #Push
  - id: 'publish'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
          docker push gcr.io/$PROJECT_ID/hello:${SHORT_SHA}
          docker push gcr.io/$PROJECT_ID/hello:${_IMAGE_TAG}
          docker push gcr.io/$PROJECT_ID/hello:latest

  # Deploy to GKE
  - id: 'deploy-gke'
    name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=k8s
    - --location=us-east1-b
    - --cluster=temp-c
    - --image=gcr.io/$PROJECT_ID/hello:${_IMAGE_TAG}

substitutions:
  _IMAGE_TAG: ${TAG_NAME}